name: Versioned Deploy Flask App

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy specific version to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Deploying version: ${{ github.ref_name }}"

            APP_DIR="/home/cvapp/cv_generator/cv-generator"

            if [ ! -d "$APP_DIR/.git" ]; then
              echo "Repo not found. Cloning..."
              rm -rf "$APP_DIR"
              git clone https://github.com/saujanya07-csit/cv_generator.git "$APP_DIR"
            fi

            cd "$APP_DIR"

            echo "Fetching tags..."
            git fetch origin --tags

            echo "Checking out version..."
            git checkout ${{ github.ref_name }}

            echo "Installing dependencies..."
            /home/cvapp/cv_generator/cv-generator/venv/bin/pip install -r requirements.txt

            echo "Restarting service..."
            sudo systemctl restart cvgen

            echo "Checking status..."
            sudo systemctl status cvgen --no-pager
